# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 617)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: #f0f0f0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.label_output_plot = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_output_plot.setGeometry(QtCore.QRect(300, 290, 141, 16))
        self.label_output_plot.setObjectName("label_output_plot")
        self.groupBox_input_parameters = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_input_parameters.setGeometry(QtCore.QRect(0, 0, 271, 501))
        self.groupBox_input_parameters.setStyleSheet("QGroupBox {\n"
"    background-color: #2e317c;\n"
"    color: white;             \n"
"    font-weight: bold;\n"
"   font-size: 20px;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-position: top center; \n"
"    padding: 5px;\n"
"}")
        self.groupBox_input_parameters.setObjectName("groupBox_input_parameters")
        self.optimizeButton = QtWidgets.QPushButton(parent=self.groupBox_input_parameters)
        self.optimizeButton.setGeometry(QtCore.QRect(20, 420, 221, 31))
        self.optimizeButton.setStyleSheet("                QPushButton {\n"
"                        background-color: white;  \n"
"                        color: #282B6A;\n"
"                        border-radius: 8px;\n"
"                        padding: 6px 12px;\n"
"                        font-weight: bold;\n"
"                        font-size: 14px;\n"
"                }\n"
"\n"
"                QPushButton:hover {\n"
"                        background-color: #E0E0FF; \n"
"                        color: #1A1D4F; \n"
"                }")
        self.optimizeButton.setObjectName("optimizeButton")
        self.groupBox_algorithm_parameters = QtWidgets.QGroupBox(parent=self.groupBox_input_parameters)
        self.groupBox_algorithm_parameters.setGeometry(QtCore.QRect(10, 200, 251, 211))
        self.groupBox_algorithm_parameters.setStyleSheet("QGroupBox {\n"
"    background-color: #DADADA; \n"
"    color: white;            \n"
"    font-weight: bold;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 21px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_algorithm_parameters.setTitle("")
        self.groupBox_algorithm_parameters.setObjectName("groupBox_algorithm_parameters")
        self.label = QtWidgets.QLabel(parent=self.groupBox_algorithm_parameters)
        self.label.setGeometry(QtCore.QRect(10, 0, 221, 31))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: black;\n"
"    border: 2px solid black;\n"
"    border-radius: 8px;\n"
"    color: white;\n"
"    font: bold 12pt \"Segoe UI\";  \n"
"    padding-left: 6px;\n"
"}")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=self.groupBox_algorithm_parameters)
        self.widget.setGeometry(QtCore.QRect(10, 48, 231, 156))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Iteration = QtWidgets.QLabel(parent=self.widget)
        self.label_Iteration.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_Iteration.setObjectName("label_Iteration")
        self.gridLayout_2.addWidget(self.label_Iteration, 0, 0, 1, 1)
        self.textEdit_Iteration = QtWidgets.QLineEdit(parent=self.widget)
        self.textEdit_Iteration.setStyleSheet("QLineEdit {\n"
"    background-color: #EEE8F0;\n"
"    border: 1px solid #999;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}")
        self.textEdit_Iteration.setObjectName("textEdit_Iteration")
        self.gridLayout_2.addWidget(self.textEdit_Iteration, 0, 1, 1, 1)
        self.label_Fireflies = QtWidgets.QLabel(parent=self.widget)
        self.label_Fireflies.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_Fireflies.setObjectName("label_Fireflies")
        self.gridLayout_2.addWidget(self.label_Fireflies, 1, 0, 1, 1)
        self.textEdit_Fireflies = QtWidgets.QLineEdit(parent=self.widget)
        self.textEdit_Fireflies.setStyleSheet("QLineEdit {\n"
"    background-color: #EEE8F0;\n"
"    border: 1px solid #999;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}")
        self.textEdit_Fireflies.setObjectName("textEdit_Fireflies")
        self.gridLayout_2.addWidget(self.textEdit_Fireflies, 1, 1, 1, 1)
        self.label_Alpha = QtWidgets.QLabel(parent=self.widget)
        self.label_Alpha.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_Alpha.setObjectName("label_Alpha")
        self.gridLayout_2.addWidget(self.label_Alpha, 2, 0, 1, 1)
        self.textEdit_Alpha = QtWidgets.QLineEdit(parent=self.widget)
        self.textEdit_Alpha.setStyleSheet("QLineEdit {\n"
"    background-color: #EEE8F0;\n"
"    border: 1px solid #999;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}")
        self.textEdit_Alpha.setObjectName("textEdit_Alpha")
        self.gridLayout_2.addWidget(self.textEdit_Alpha, 2, 1, 1, 1)
        self.label_Gamma = QtWidgets.QLabel(parent=self.widget)
        self.label_Gamma.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_Gamma.setObjectName("label_Gamma")
        self.gridLayout_2.addWidget(self.label_Gamma, 3, 0, 1, 1)
        self.textEdit_Gamma = QtWidgets.QLineEdit(parent=self.widget)
        self.textEdit_Gamma.setStyleSheet("QLineEdit {\n"
"    background-color: #EEE8F0;\n"
"    border: 1px solid #999;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}")
        self.textEdit_Gamma.setObjectName("textEdit_Gamma")
        self.gridLayout_2.addWidget(self.textEdit_Gamma, 3, 1, 1, 1)
        self.label_lambda = QtWidgets.QLabel(parent=self.widget)
        self.label_lambda.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_lambda.setObjectName("label_lambda")
        self.gridLayout_2.addWidget(self.label_lambda, 4, 0, 1, 1)
        self.textEdit_lambda = QtWidgets.QLineEdit(parent=self.widget)
        self.textEdit_lambda.setStyleSheet("QLineEdit {\n"
"    background-color: #EEE8F0;\n"
"    border: 1px solid #999;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}")
        self.textEdit_lambda.setObjectName("textEdit_lambda")
        self.gridLayout_2.addWidget(self.textEdit_lambda, 4, 1, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.groupBox_input_parameters)
        self.line.setGeometry(QtCore.QRect(10, 30, 251, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(parent=self.groupBox_input_parameters)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 460, 221, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.resetButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.resetButton.setStyleSheet("                QPushButton {\n"
"                        background-color: white;  \n"
"                        color: #282B6A;\n"
"                        border-radius: 8px;\n"
"                        padding: 6px 12px;\n"
"                        font-weight: bold;\n"
"                        font-size: 14px;\n"
"                }\n"
"\n"
"                QPushButton:hover {\n"
"                        background-color: #E0E0FF; \n"
"                        color: #1A1D4F; \n"
"                }")
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout.addWidget(self.resetButton)
        self.exportButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.exportButton.setStyleSheet("                QPushButton {\n"
"                        background-color: white;  \n"
"                        color: #282B6A;\n"
"                        border-radius: 8px;\n"
"                        padding: 6px 12px;\n"
"                        font-weight: bold;\n"
"                        font-size: 14px;\n"
"                }\n"
"\n"
"                QPushButton:hover {\n"
"                        background-color: #E0E0FF; \n"
"                        color: #1A1D4F; \n"
"                }")
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout.addWidget(self.exportButton)
        self.groupBox_initial_window = QtWidgets.QGroupBox(parent=self.groupBox_input_parameters)
        self.groupBox_initial_window.setGeometry(QtCore.QRect(10, 48, 251, 141))
        self.groupBox_initial_window.setStyleSheet("QGroupBox {\n"
"    background-color: #DADADA; \n"
"    color: white;             \n"
"    font-weight: bold;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 21px; \n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; \n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_initial_window.setTitle("")
        self.groupBox_initial_window.setObjectName("groupBox_initial_window")
        self.label_initial_window = QtWidgets.QLabel(parent=self.groupBox_initial_window)
        self.label_initial_window.setGeometry(QtCore.QRect(40, 0, 161, 31))
        self.label_initial_window.setStyleSheet("QLabel {\n"
"    background-color: black;\n"
"    border: 2px solid black;\n"
"    border-radius: 8px;\n"
"    color: white;\n"
"    font: bold 12pt \"Segoe UI\";  \n"
"    padding-left: 6px;\n"
"}")
        self.label_initial_window.setObjectName("label_initial_window")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.groupBox_initial_window)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 228, 92))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_window_length = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_window_length.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_window_length.setObjectName("label_window_length")
        self.gridLayout.addWidget(self.label_window_length, 0, 0, 1, 1)
        self.textEdit_window_length = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.textEdit_window_length.setStyleSheet("QLineEdit {\n"
"    background-color: #EEE8F0;\n"
"    border: 1px solid #999;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}")
        self.textEdit_window_length.setObjectName("textEdit_window_length")
        self.gridLayout.addWidget(self.textEdit_window_length, 0, 1, 1, 1)
        self.label_Beta = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_Beta.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_Beta.setObjectName("label_Beta")
        self.gridLayout.addWidget(self.label_Beta, 1, 0, 1, 1)
        self.textEdit_Beta = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.textEdit_Beta.setStyleSheet("QLineEdit {\n"
"    background-color: #EEE8F0;\n"
"    border: 1px solid #999;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}")
        self.textEdit_Beta.setObjectName("textEdit_Beta")
        self.gridLayout.addWidget(self.textEdit_Beta, 1, 1, 1, 1)
        self.label_freqResolution = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_freqResolution.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_freqResolution.setObjectName("label_freqResolution")
        self.gridLayout.addWidget(self.label_freqResolution, 2, 0, 1, 1)
        self.textEdit_freqResolution = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.textEdit_freqResolution.setStyleSheet("QLineEdit {\n"
"    background-color: #EEE8F0;\n"
"    border: 1px solid #999;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}")
        self.textEdit_freqResolution.setObjectName("textEdit_freqResolution")
        self.gridLayout.addWidget(self.textEdit_freqResolution, 2, 1, 1, 1)
        self.stopButton = QtWidgets.QPushButton(parent=self.groupBox_input_parameters)
        self.stopButton.setGeometry(QtCore.QRect(10, 420, 241, 31))
        self.stopButton.setStyleSheet("                QPushButton {\n"
"                        background-color:#E0E0FF;  \n"
"                        color: #282B6A;\n"
"                        border-radius: 8px;\n"
"                        padding: 6px 12px;\n"
"                        font-weight: bold;\n"
"                        font-size: 14px;\n"
"                }\n"
"\n"
"                QPushButton:hover {\n"
"                        background-color: white; \n"
"                        color: #1A1D4F; \n"
"                }")
        self.stopButton.setObjectName("stopButton")
        self.groupBox_output_result = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_output_result.setGeometry(QtCore.QRect(280, 10, 501, 221))
        self.groupBox_output_result.setStyleSheet("QGroupBox {\n"
"    background-color: #DADADA;\n"
"    color: black;            \n"
"    font-weight: bold;\n"
"   font-size: 20px;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"QGroupBox::title {\n"
"    padding: 5px;\n"
"}")
        self.groupBox_output_result.setTitle("")
        self.groupBox_output_result.setObjectName("groupBox_output_result")
        self.label_output_result = QtWidgets.QLabel(parent=self.groupBox_output_result)
        self.label_output_result.setGeometry(QtCore.QRect(0, 0, 501, 31))
        self.label_output_result.setStyleSheet("QLabel {\n"
"    background-color: #336F55;\n"
"    border-radius: 8px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14pt;\n"
"    padding-left: 6px;\n"
"}")
        self.label_output_result.setObjectName("label_output_result")
        self.splitter_4 = QtWidgets.QSplitter(parent=self.groupBox_output_result)
        self.splitter_4.setGeometry(QtCore.QRect(10, 40, 477, 171))
        self.splitter_4.setStyleSheet("QSplitter::handle:vertical {\n"
"    background-color: #DADADA;\n"
"}")
        self.splitter_4.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_2 = QtWidgets.QSplitter(parent=self.splitter_4)
        self.splitter_2.setStyleSheet("QSplitter::handle:horizontal {\n"
"    background-color: #DADADA;\n"
"}")
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.splitter_2)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_pslr_original = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_pslr_original.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_pslr_original.setObjectName("label_pslr_original")
        self.gridLayout_3.addWidget(self.label_pslr_original, 1, 0, 1, 1)
        self.textEdit_pl_original = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.textEdit_pl_original.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #aaaaaa;\n"
"    border-radius: 4px;\n"
"    padding: 2px 4px;\n"
"    color: #000000;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"}")
        self.textEdit_pl_original.setObjectName("textEdit_pl_original")
        self.gridLayout_3.addWidget(self.textEdit_pl_original, 2, 1, 1, 1)
        self.label_mw_original = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_mw_original.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_mw_original.setObjectName("label_mw_original")
        self.gridLayout_3.addWidget(self.label_mw_original, 0, 0, 1, 1)
        self.label_pl_original = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_pl_original.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_pl_original.setObjectName("label_pl_original")
        self.gridLayout_3.addWidget(self.label_pl_original, 2, 0, 1, 1)
        self.textEdit_mw_original = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.textEdit_mw_original.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #aaaaaa;\n"
"    border-radius: 4px;\n"
"    padding: 2px 4px;\n"
"    color: #000000;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"}")
        self.textEdit_mw_original.setObjectName("textEdit_mw_original")
        self.gridLayout_3.addWidget(self.textEdit_mw_original, 0, 1, 1, 1)
        self.textEdit_pslr_original = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.textEdit_pslr_original.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #aaaaaa;\n"
"    border-radius: 4px;\n"
"    padding: 2px 4px;\n"
"    color: #000000;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"}")
        self.textEdit_pslr_original.setObjectName("textEdit_pslr_original")
        self.gridLayout_3.addWidget(self.textEdit_pslr_original, 1, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.splitter_2)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_mw_optimized = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_mw_optimized.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_mw_optimized.setObjectName("label_mw_optimized")
        self.gridLayout_4.addWidget(self.label_mw_optimized, 0, 0, 1, 1)
        self.textEdit_mw_optimized = QtWidgets.QLineEdit(parent=self.layoutWidget3)
        self.textEdit_mw_optimized.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #aaaaaa;\n"
"    border-radius: 4px;\n"
"    padding: 2px 4px;\n"
"    color: #000000;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"}")
        self.textEdit_mw_optimized.setObjectName("textEdit_mw_optimized")
        self.gridLayout_4.addWidget(self.textEdit_mw_optimized, 0, 1, 1, 1)
        self.label_pslr_optimized = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_pslr_optimized.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_pslr_optimized.setObjectName("label_pslr_optimized")
        self.gridLayout_4.addWidget(self.label_pslr_optimized, 1, 0, 1, 1)
        self.textEdit_pslr_optimized = QtWidgets.QLineEdit(parent=self.layoutWidget3)
        self.textEdit_pslr_optimized.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #aaaaaa;\n"
"    border-radius: 4px;\n"
"    padding: 2px 4px;\n"
"    color: #000000;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"}")
        self.textEdit_pslr_optimized.setObjectName("textEdit_pslr_optimized")
        self.gridLayout_4.addWidget(self.textEdit_pslr_optimized, 1, 1, 1, 1)
        self.label_pl_optimized = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_pl_optimized.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_pl_optimized.setObjectName("label_pl_optimized")
        self.gridLayout_4.addWidget(self.label_pl_optimized, 2, 0, 1, 1)
        self.textEdit_pl_optimized = QtWidgets.QLineEdit(parent=self.layoutWidget3)
        self.textEdit_pl_optimized.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #aaaaaa;\n"
"    border-radius: 4px;\n"
"    padding: 2px 4px;\n"
"    color: #000000;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"}")
        self.textEdit_pl_optimized.setObjectName("textEdit_pl_optimized")
        self.gridLayout_4.addWidget(self.textEdit_pl_optimized, 2, 1, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(parent=self.splitter_4)
        self.splitter_3.setStyleSheet("QSplitter::handle:horizontal {\n"
"    background-color:  #DADADA;\n"
"}")
        self.splitter_3.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_final_window = QtWidgets.QLabel(parent=self.splitter_3)
        self.label_final_window.setStyleSheet("QLabel {\n"
"    color: #333333;           \n"
"    background-color: transparent; \n"
"    font: bold 10pt \"Segoe UI\";  \n"
"    padding: 2px;                 \n"
"}")
        self.label_final_window.setObjectName("label_final_window")
        self.textEdit_final_window = QtWidgets.QTextEdit(parent=self.splitter_3)
        self.textEdit_final_window.setStyleSheet("QTextEdit {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #aaaaaa;\n"
"    border-radius: 4px;\n"
"    padding: 2px 4px;\n"
"}")
        self.textEdit_final_window.setObjectName("textEdit_final_window")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 240, 501, 311))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: #DADADA;\n"
"    color: black;            \n"
"    font-weight: bold;\n"
"   font-size: 20px;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"QGroupBox::title {\n"
"    padding: 5px;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.tabWidget_Plots = QtWidgets.QTabWidget(parent=self.groupBox_2)
        self.tabWidget_Plots.setGeometry(QtCore.QRect(10, 40, 481, 261))
        self.tabWidget_Plots.setStyleSheet("                QTabBar::tab {\n"
"                        background: #DAD0E5;\n"
"                        color: black;\n"
"                        border: 1px solid #888;\n"
"                        border-bottom: none;\n"
"                        border-top-left-radius: 5px;\n"
"                        border-top-right-radius: 5px;\n"
"                        padding: 6px 12px;\n"
"                        font-weight: bold;\n"
"                }\n"
"\n"
"                QTabBar::tab:selected {\n"
"                        background: white;\n"
"                        color: black;\n"
"                }\n"
"\n"
"                QTabWidget::pane {\n"
"                        background: white;\n"
"                        border: 2px solid #444;\n"
"                        border-radius: 5px;\n"
"                        top: -1px;\n"
"                }")
        self.tabWidget_Plots.setObjectName("tabWidget_Plots")
        self.tab_time_domain = QtWidgets.QWidget()
        self.tab_time_domain.setObjectName("tab_time_domain")
        self.tabWidget_Plots.addTab(self.tab_time_domain, "")
        self.tab_frequancy_response = QtWidgets.QWidget()
        self.tab_frequancy_response.setObjectName("tab_frequancy_response")
        self.tabWidget_Plots.addTab(self.tab_frequancy_response, "")
        self.label_output_plot_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_output_plot_2.setGeometry(QtCore.QRect(0, 0, 501, 31))
        self.label_output_plot_2.setStyleSheet("QLabel {\n"
"    background-color: #336F55;\n"
"    border-radius: 8px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14pt;\n"
"    padding-left: 6px;\n"
"}")
        self.label_output_plot_2.setObjectName("label_output_plot_2")
        self.label_Error_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Error_2.setGeometry(QtCore.QRect(0, 560, 791, 31))
        self.label_Error_2.setAutoFillBackground(False)
        self.label_Error_2.setStyleSheet("QLabel {\n"
"    background-color: #F0F0F0;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"    padding-left: 6px;\n"
"}")
        self.label_Error_2.setObjectName("label_Error_2")
        self.groupBox_about_us = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_about_us.setGeometry(QtCore.QRect(0, 510, 271, 41))
        self.groupBox_about_us.setStyleSheet("QGroupBox {\n"
"    background-color: white; \n"
"    color: black;             \n"
"    font-weight: bold;\n"
"   font-size: 15px;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"}")
        self.groupBox_about_us.setTitle("")
        self.groupBox_about_us.setObjectName("groupBox_about_us")
        self.splitter = QtWidgets.QSplitter(parent=self.groupBox_about_us)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 251, 25))
        self.splitter.setStyleSheet("QSplitter::handle:horizontal {\n"
"    background-color:white;\n"
"}")
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.about_us_Button = QtWidgets.QPushButton(parent=self.splitter)
        self.about_us_Button.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;           \n"
"    color: black;             \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    font-weight: bold;        \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/group-chat.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.about_us_Button.setIcon(icon)
        self.about_us_Button.setIconSize(QtCore.QSize(30, 30))
        self.about_us_Button.setObjectName("about_us_Button")
        self.about_Software_Button = QtWidgets.QPushButton(parent=self.splitter)
        self.about_Software_Button.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;           \n"
"    color: black;             \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    font-weight: bold;        \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./images/software-application.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.about_Software_Button.setIcon(icon1)
        self.about_Software_Button.setIconSize(QtCore.QSize(25, 25))
        self.about_Software_Button.setObjectName("about_Software_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_Plots.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " Kaiser Window Optimizer  "))
        self.label_output_plot.setText(_translate("MainWindow", "Output Plot"))
        self.groupBox_input_parameters.setTitle(_translate("MainWindow", "Input Parameters"))
        self.optimizeButton.setText(_translate("MainWindow", "Optimize"))
        self.label.setText(_translate("MainWindow", "Algorithm Parameters"))
        self.label_Iteration.setText(_translate("MainWindow", "Iteration"))
        self.label_Fireflies.setText(_translate("MainWindow", "Number of Fireflies"))
        self.label_Alpha.setText(_translate("MainWindow", "Alpha"))
        self.label_Gamma.setText(_translate("MainWindow", "Gamma"))
        self.label_lambda.setText(_translate("MainWindow", "Lambda"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.exportButton.setText(_translate("MainWindow", "Export"))
        self.label_initial_window.setText(_translate("MainWindow", "Initial Window "))
        self.label_window_length.setText(_translate("MainWindow", "Window length"))
        self.label_Beta.setText(_translate("MainWindow", "Beta"))
        self.label_freqResolution.setText(_translate("MainWindow", "Resolution"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.label_output_result.setText(_translate("MainWindow", "Output Results"))
        self.label_pslr_original.setText(_translate("MainWindow", "Original_PSLR:"))
        self.label_mw_original.setText(_translate("MainWindow", "Original_MW:"))
        self.label_pl_original.setText(_translate("MainWindow", "Original_PL:"))
        self.label_mw_optimized.setText(_translate("MainWindow", "Optimized_MW:"))
        self.label_pslr_optimized.setText(_translate("MainWindow", "Optimized_PSLR:"))
        self.label_pl_optimized.setText(_translate("MainWindow", "Optimized_PL:"))
        self.label_final_window.setText(_translate("MainWindow", "Optimized_Window:"))
        self.tabWidget_Plots.setTabText(self.tabWidget_Plots.indexOf(self.tab_time_domain), _translate("MainWindow", "Time-Domain"))
        self.tabWidget_Plots.setTabText(self.tabWidget_Plots.indexOf(self.tab_frequancy_response), _translate("MainWindow", "Frequency Response"))
        self.label_output_plot_2.setText(_translate("MainWindow", "Output Plot"))
        self.label_Error_2.setText(_translate("MainWindow", "Welcome!"))
        self.about_us_Button.setText(_translate("MainWindow", "About Us"))
        self.about_Software_Button.setText(_translate("MainWindow", "About Software"))
